package br.com.blacksheep;

public enum Tags {

	AGENDAMENTO("AGENDAMENTO"),
	AGENDAMENTO_EXECUCAO_INICIO("EXECUCAOINICIO"),
	AGENDAMENTO_EXECUCAO_INICIO_HORA("HORA"),
	AGENDAMENTO_EXECUCAO_INICIO_MINUTO("MINUTO"),
	AGENDAMENTO_EXECUCAO_INTERVALO("EXECUCAOINTERVALO"),
	AGENDAMENTO_EXECUCAO_INTERVALO_HORA("HORA"),
	AGENDAMENTO_EXECUCAO_INTERVALO_MINUTO("MINUTO"),
	BANCO("BANCO"),
	BANCO_DATABASE_TYPE_ENUM("DATABASETYPEENUM"),
	BANCO_SERVER("SERVER"),
	BANCO_DATABASE("DATABASE"),
	BANCO_USER("USER"),
	BANCO_PASSWORD("PASSWORD");

	private String name;

	private Tags(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

}
